from django.db import models

# Create your models here.
from .CaGacVBModel import CaGacVBModel
from .CapBacModel import CapBacModel
from .CapDonViModel import CapDonViModel
from .CBHaSiQuanModel import CBHaSiQuanModel
from .ChienSiModel import ChienSiModel
from .CVQNCNModel import CVQNCNModel
from .CVSiQuanModel import CVSiQuanModel
from .DonViModel import DonViModel
from .HocVienModel import HocVienModel
from .KhachQNCNModel import KhachQNCNModel
from .KhachSiQuanModel import KhachSiQuanModel
from .KhachTDChiTietModel import KhachTDChiTietModel
from .KhachTheoDoanModel import KhachTheoDoanModel
from .KhachVienChucModel import KhachVienChucModel
from .LoiViPhamModel import LoiViPhamModel
from .LSRaVaoHVModel import LSRaVaoHVModel
from .LSRaVaoQNCNModel import LSRaVaoQNCNModel
from .LSRaVaoSQModel import LSRaVaoSQModel
from .LSRaVaoVCModel import LSRaVaoVCModel
from .NhomDonViModel import NhomDonViModel
from .NhomQNCNModel import NhomQNCNModel
from .NhomSQModel import NhomSQModel
from .NhomVCQPModel import NhomVCQPModel
from .PCTrucBanModel import PCTrucBanModel
from .PCVeBinhChiTietModel import PCVeBinhChiTietModel
from .PCVeBinhModel import PCVeBinhModel
from .QNCNModel import QNCNModel
from .QuyenHVModel import QuyenHVModel
from .QuyenModel import QuyenModel
from .QuyenNhomQNCNModel import QuyenNhomQNCNModel
from .QuyenNhomSQModel import QuyenNhomSQModel
from .QuyenNhomVCModel import QuyenNhomVCModel
from .RNNgayHanhChinhModel import RNNgayHanhChinhModel
from .RNNHCThoiGianModel import RNNHCThoiGianModel
from .SiQuanModel import SiQuanModel
from .TheQNCNModel import TheQNCNModel
from .TheQNCNNamModel import TheQNCNNamModel
from .TheSiQuanModel import TheSiQuanModel
from .TheSiQuanNamModel import TheSiQuanNamModel
from .TheVienChucModel import TheVienChucModel
from .TheSiQuanNamModel import TheSiQuanNamModel
from .ThoiGianKhachTDModel import ThoiGianKhachTDModel
from .ThoiGianQuyenModel import ThoiGianQuyenModel
from .VienChucQPModel import VienChucQPModel
from .ViPhamHVModel import ViPhamHVModel
from .ViPhamQNCNModel import ViPhamQNCNModel
from .ViPhamSQModel import ViPhamSQModel
from .ViPhamVCModel import ViPhamVCModel
from .KhachModel import KhachModel
from .TheKhachModel import TheKhachModel
from .QNCN_NhomQNCNModel import QNCN_NhomQNCNModel
from .SQ_NhomSQModel import SQ_NhomSQModel
from .VC_NhomVCModel import VC_NhomVCModel
from .SQ_CVModel import SQ_CVModel
from .SQ_DVModel import SQ_DVModel
from .LoaiKhachModel import LoaiKhachModel
from .CongGacModel import CongGacModel
from .KhachHocVienModel import KhachHocVienModel
from .PCGacNgayModel import PCGacNgayModel