# Generated by Django 5.1 on 2024-08-26 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaBacVCModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ca', models.IntegerField()),
                ('TGBatDau', models.TimeField()),
                ('TGKetThuc', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CapBacModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenCapBac', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='CapNhomDonViModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cap', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CBHaSiQuancModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenCapBac', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='KhachModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HoTenKhach', models.CharField(max_length=30)),
                ('SoCCCD', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='LoiViPhamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenLoi', models.CharField(max_length=50)),
                ('GiaiThich', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NhomDonViModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenNhom', models.CharField(max_length=50)),
                ('GhiChu', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NhomQNCNModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenNhom', models.CharField(max_length=50)),
                ('GhiChu', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NhomSQModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenNhom', models.CharField(max_length=50)),
                ('GhiChu', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NhomVCQPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenNhom', models.CharField(max_length=50)),
                ('GhiChu', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QuyenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenQuyen', models.CharField(max_length=20)),
                ('GiaiThich', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TheKhachModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoThe', models.IntegerField()),
                ('TrangThai', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DonViModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenDonVi', models.CharField(max_length=255)),
                ('DiaDiem', models.CharField(max_length=255)),
                ('MaDonVi', models.CharField(max_length=50, unique=True)),
                ('SoDienThoai', models.CharField(max_length=15)),
                ('CapNhomDonVi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.capnhomdonvimodel')),
                ('id_DonViCapTren', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='don_vi_con', to='model.donvimodel')),
            ],
        ),
        migrations.CreateModel(
            name='ChienSiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HoTen', models.CharField(max_length=50)),
                ('NgaySinh', models.DateField()),
                ('NgayNhapNgu', models.DateField()),
                ('SoCanCuoc', models.CharField(max_length=20)),
                ('QueQuan', models.CharField(max_length=60)),
                ('NoiO', models.CharField(max_length=60)),
                ('CapBac', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.cbhasiquancmodel')),
                ('DonVi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.donvimodel')),
            ],
        ),
        migrations.CreateModel(
            name='HocVienModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HoTen', models.CharField(max_length=50)),
                ('NgaySinh', models.DateField()),
                ('MaQuanNhan', models.CharField(max_length=20)),
                ('NgayNhapNgu', models.DateField()),
                ('SoCanCuoc', models.CharField(max_length=20)),
                ('QueQuan', models.CharField(max_length=60)),
                ('NoiO', models.CharField(max_length=60)),
                ('CapBac', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.cbhasiquancmodel')),
                ('DonVi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.donvimodel')),
            ],
        ),
        migrations.CreateModel(
            name='KhachTheoDoanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DonVi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.donvimodel')),
                ('KhachDaiDien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.khachmodel')),
            ],
        ),
        migrations.CreateModel(
            name='LSRaVaoHVModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('So', models.CharField(max_length=2)),
                ('TGRa', models.DateTimeField()),
                ('TGVao', models.DateTimeField(null=True)),
                ('DonVi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.donvimodel')),
            ],
        ),
        migrations.AddField(
            model_name='capnhomdonvimodel',
            name='id_NhomDonVi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.nhomdonvimodel'),
        ),
        migrations.CreateModel(
            name='CVQNCNModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenChucVu', models.CharField(max_length=50)),
                ('id_CapNhomDonVi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.capnhomdonvimodel')),
                ('id_NhomQNCN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.nhomqncnmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CVSiQuanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenChucVu', models.CharField(max_length=50)),
                ('id_CapNhomDonVi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.capnhomdonvimodel')),
                ('id_NhomSQ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.nhomsqmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PCVeBinhModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ngay', models.DateField()),
                ('Cong', models.CharField(max_length=10)),
                ('Ca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.cabacvcmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PCVeBinhChiTietModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChienSi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.chiensimodel')),
                ('PCVB', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.pcvebinhmodel')),
            ],
        ),
        migrations.CreateModel(
            name='QNCNModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HoTen', models.CharField(max_length=50)),
                ('NgaySinh', models.DateField()),
                ('MaQuanNhan', models.CharField(max_length=20)),
                ('NgayNhapNgu', models.DateField()),
                ('SoCanCuoc', models.CharField(max_length=20)),
                ('QueQuan', models.CharField(max_length=60)),
                ('NoiO', models.CharField(max_length=60)),
                ('CapBac', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.capbacmodel')),
                ('ChucVu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.cvqncnmodel')),
                ('DonVi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.donvimodel')),
                ('NhomSQ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.nhomqncnmodel')),
            ],
        ),
        migrations.CreateModel(
            name='KhachQNCNModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TheKhach', models.CharField(max_length=5)),
                ('HoTenKhach', models.CharField(max_length=30)),
                ('CCKhach', models.CharField(max_length=20)),
                ('ThoiGianBatDau', models.DateTimeField()),
                ('ThoiGianKetThuc', models.DateTimeField(null=True)),
                ('QNCN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.qncnmodel')),
            ],
        ),
        migrations.CreateModel(
            name='QuyenHVModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quyen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='model.quyenmodel')),
            ],
        ),
        migrations.CreateModel(
            name='QuyenNhomQNCNModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NhomQNCN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.nhomqncnmodel')),
                ('Quyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.quyenmodel')),
            ],
        ),
        migrations.CreateModel(
            name='QuyenNhomSQModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NhomSQ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.nhomsqmodel')),
                ('Quyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.quyenmodel')),
            ],
        ),
        migrations.CreateModel(
            name='QuyenNhomVCModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NhomVC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.nhomvcqpmodel')),
                ('Quyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.quyenmodel')),
            ],
        ),
        migrations.CreateModel(
            name='RNNgayHanhChinhModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LyDo', models.CharField(max_length=50)),
                ('DiaDiem', models.CharField(max_length=255)),
                ('HocVien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.hocvienmodel')),
            ],
        ),
        migrations.CreateModel(
            name='RNNHCThoiGianModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DKRa', models.DateTimeField()),
                ('DKVao', models.DateTimeField()),
                ('TGRa', models.DateTimeField(null=True)),
                ('TGVao', models.DateTimeField(null=True)),
                ('RNNgayHanhChinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.rnngayhanhchinhmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SiQuanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HoTen', models.CharField(max_length=50)),
                ('NgaySinh', models.DateField()),
                ('MaQuanNhan', models.CharField(max_length=20)),
                ('NgayNhapNgu', models.DateField()),
                ('SoCanCuoc', models.CharField(max_length=20)),
                ('QueQuan', models.CharField(max_length=60)),
                ('NoiO', models.CharField(max_length=60)),
                ('CapBac', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.capbacmodel')),
                ('ChucVu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.cvsiquanmodel')),
                ('DonVi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.donvimodel')),
                ('NhomSQ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.nhomsqmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PCTrucBanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ngay', models.DateField()),
                ('TBPho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pctrucban_tbt', to='model.siquanmodel')),
                ('TBTruong', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pctrucban_tbp', to='model.siquanmodel')),
            ],
        ),
        migrations.CreateModel(
            name='KhachTDChiTietModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Khach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.khachmodel')),
                ('DoanKhach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.khachtheodoanmodel')),
                ('TheKhach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.thekhachmodel')),
            ],
        ),
        migrations.CreateModel(
            name='KhachSiQuanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThoiGianBatDau', models.DateTimeField()),
                ('ThoiGianKetThuc', models.DateTimeField(null=True)),
                ('GhiChu', models.CharField(max_length=255)),
                ('Khach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.khachmodel')),
                ('SiQuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.siquanmodel')),
                ('TheKhach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.thekhachmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TheQNCNModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoThe', models.CharField(max_length=5, unique=True)),
                ('QNCN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.qncnmodel')),
            ],
        ),
        migrations.CreateModel(
            name='LSRaVaoQNCNModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThoiGian', models.DateTimeField()),
                ('TrangThai', models.BooleanField()),
                ('QNCN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.qncnmodel')),
                ('SoThe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.theqncnmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TheQNCNNamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nam', models.PositiveIntegerField()),
                ('The', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.theqncnmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TheSiQuanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoThe', models.CharField(max_length=5, unique=True)),
                ('SiQuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.siquanmodel')),
            ],
        ),
        migrations.CreateModel(
            name='LSRaVaoSQModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThoiGian', models.DateTimeField()),
                ('TrangThai', models.BooleanField()),
                ('SiQuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.siquanmodel')),
                ('SoThe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.thesiquanmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TheSiQuanNamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nam', models.PositiveIntegerField()),
                ('The', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.thesiquanmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ThoiGianKhachTDModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DKVao', models.DateTimeField()),
                ('DKRa', models.DateTimeField()),
                ('TGVao', models.DateTimeField(null=True)),
                ('TGRa', models.DateTimeField(null=True)),
                ('DoanKhach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.khachtheodoanmodel')),
                ('SQDon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='model.siquanmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ThoiGianQuyenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Thu', models.IntegerField()),
                ('TGRa', models.TimeField()),
                ('TGVap', models.TimeField()),
                ('Quyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.quyenmodel')),
            ],
        ),
        migrations.CreateModel(
            name='VienChucQPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HoTen', models.CharField(max_length=50)),
                ('NgaySinh', models.DateField()),
                ('NgayBatDauLamViec', models.DateField()),
                ('SoCanCuoc', models.CharField(max_length=20)),
                ('QueQuan', models.CharField(max_length=60)),
                ('NoiO', models.CharField(max_length=60)),
                ('DonVi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.donvimodel')),
                ('NhomVCQP', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.nhomvcqpmodel')),
            ],
        ),
        migrations.CreateModel(
            name='VC_NhomVCModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NhomVC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.nhomvcqpmodel')),
                ('VienChuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.vienchucqpmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TheVienChucModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoThe', models.CharField(max_length=5, unique=True)),
                ('VienChuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.vienchucqpmodel')),
            ],
        ),
        migrations.CreateModel(
            name='LSRaVaoVCModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThoiGian', models.DateTimeField()),
                ('TrangThai', models.BooleanField()),
                ('SoThe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.thevienchucmodel')),
                ('VienChuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.vienchucqpmodel')),
            ],
        ),
        migrations.CreateModel(
            name='KhachVienChucModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThoiGianBatDau', models.DateTimeField()),
                ('ThoiGianKetThuc', models.DateTimeField(null=True)),
                ('GhiChu', models.CharField(max_length=255)),
                ('Khach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.khachmodel')),
                ('TheKhach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.thekhachmodel')),
                ('VienChuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.vienchucqpmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ViPhamHVModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThoiGian', models.DateTimeField()),
                ('GhiChu', models.CharField(max_length=255)),
                ('HocVien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.hocvienmodel')),
                ('LoiViPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.loiviphammodel')),
            ],
        ),
        migrations.CreateModel(
            name='ViPhamQNCNModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThoiGian', models.DateTimeField()),
                ('GhiChu', models.CharField(max_length=255)),
                ('LoiViPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.loiviphammodel')),
                ('QNCN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.qncnmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ViPhamSQModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThoiGian', models.DateTimeField()),
                ('GhiChu', models.CharField(max_length=255)),
                ('LoiViPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.loiviphammodel')),
                ('SiQuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.siquanmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ViPhamVCModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThoiGian', models.DateTimeField()),
                ('GhiChu', models.CharField(max_length=255)),
                ('LoiViPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.loiviphammodel')),
                ('VienChuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.vienchucqpmodel')),
            ],
        ),
        migrations.CreateModel(
            name='QNCN_NhomQNCNModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NhomQNCN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.nhomqncnmodel')),
                ('QNCN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.qncnmodel')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('QNCN', 'NhomQNCN'), name='unique_QNCN_NhomQNCN')],
            },
        ),
        migrations.CreateModel(
            name='SQ_NhomSQModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NhomSiQuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.nhomsqmodel')),
                ('SiQuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.siquanmodel')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('SiQuan', 'NhomSiQuan'), name='unique_SiQuan_NhomSiQuan')],
            },
        ),
    ]
