# Generated by Django 5.1 on 2024-10-02 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaGacVBModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ca', models.CharField(max_length=20)),
                ('TGBatDau', models.TimeField()),
                ('TGKetThuc', models.TimeField()),
                ('TrangThai', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CapBacModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenCapBac', models.CharField(max_length=15)),
                ('TinhTrang', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CBHaSiQuanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenCapBac', models.CharField(max_length=15)),
                ('TinhTrang', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CongGacModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenCong', models.CharField(max_length=20)),
                ('ViTri', models.CharField(max_length=50)),
                ('TrangThai', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='KhachModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HoTenKhach', models.CharField(max_length=30)),
                ('SoDinhDanh', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='LoaiKhachModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenLoaiKhach', models.CharField(max_length=50)),
                ('TrangThai', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoiViPhamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenLoi', models.CharField(max_length=50)),
                ('GiaiThich', models.CharField(max_length=255)),
                ('TinhTrang', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NhomDonViModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenNhom', models.CharField(max_length=50)),
                ('GhiChu', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NhomQNCNModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenNhom', models.CharField(max_length=50)),
                ('TinhTrang', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NhomSQModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenNhom', models.CharField(max_length=50)),
                ('TinhTrang', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NhomVCQPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenNhom', models.CharField(max_length=50)),
                ('TinhTrang', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuyenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenQuyen', models.CharField(max_length=50)),
                ('GiaiThich', models.CharField(max_length=255, null=True)),
                ('TinhTrang', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TheKhachModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoThe', models.CharField(max_length=5)),
                ('TrangThai', models.BooleanField(default=True)),
                ('DangSuDung', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TheVienChucModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoThe', models.CharField(max_length=5, unique=True)),
                ('TrangThai', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('doituong', models.CharField(choices=[('vanphong', 'Văn phòng'), ('trucban', 'Trực Ban'), ('vebinh', 'Vệ Binh')], default='vebinh', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CapDonViModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ten', models.CharField(max_length=20)),
                ('TinhTrang', models.BooleanField(default=True)),
                ('CapTren', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CapNhomTren', to='model.capdonvimodel')),
                ('id_NhomDonVi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.nhomdonvimodel')),
            ],
        ),
        migrations.CreateModel(
            name='CVQNCNModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenChucVu', models.CharField(max_length=50)),
                ('TinhTrang', models.BooleanField(default=True)),
                ('id_CapDonVi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.capdonvimodel')),
            ],
        ),
        migrations.CreateModel(
            name='CVSiQuanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenChucVu', models.CharField(max_length=50)),
                ('TinhTrang', models.BooleanField(default=True)),
                ('id_CapDonVi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.capdonvimodel')),
            ],
        ),
        migrations.CreateModel(
            name='DonViModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenDonVi', models.CharField(max_length=255)),
                ('DiaDiem', models.CharField(max_length=50)),
                ('MaDonVi', models.CharField(max_length=20, unique=True)),
                ('SoDienThoai', models.CharField(max_length=15)),
                ('id_CapDonVi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.capdonvimodel')),
                ('id_DonViCapTren', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='don_vi_con', to='model.donvimodel')),
            ],
        ),
        migrations.CreateModel(
            name='ChienSiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HoTen', models.CharField(max_length=50)),
                ('Ma', models.CharField(max_length=20)),
                ('NgaySinh', models.DateField()),
                ('NgayNhapNgu', models.DateField()),
                ('SoCanCuoc', models.CharField(max_length=20)),
                ('QueQuan', models.CharField(max_length=60)),
                ('NoiO', models.CharField(max_length=60)),
                ('TinhTrang', models.BooleanField(default=True)),
                ('CapBac', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.cbhasiquanmodel')),
                ('DonVi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.donvimodel')),
            ],
        ),
        migrations.CreateModel(
            name='HocVienModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HoTen', models.CharField(max_length=50)),
                ('NgaySinh', models.DateField()),
                ('MaQuanNhan', models.CharField(max_length=20)),
                ('NgayNhapNgu', models.DateField()),
                ('SoCanCuoc', models.CharField(max_length=20)),
                ('QueQuan', models.CharField(max_length=60)),
                ('NoiO', models.CharField(max_length=60)),
                ('TinhTrang', models.BooleanField(default=True)),
                ('CapBac', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.cbhasiquanmodel')),
                ('DonVi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.donvimodel')),
            ],
        ),
        migrations.CreateModel(
            name='KhachHocVienModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThoiGianBatDau', models.DateTimeField()),
                ('ThoiGianKetThuc', models.DateTimeField(null=True)),
                ('GhiChu', models.CharField(max_length=255, null=True)),
                ('HV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.hocvienmodel')),
                ('Khach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.khachmodel')),
            ],
        ),
        migrations.CreateModel(
            name='KhachTheoDoanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TinhTrang', models.BooleanField(default=True)),
                ('DonVi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.donvimodel')),
                ('KhachDaiDien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.khachmodel')),
            ],
        ),
        migrations.AddField(
            model_name='khachmodel',
            name='Loai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.loaikhachmodel'),
        ),
        migrations.CreateModel(
            name='LSRaVaoHVModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('So', models.CharField(max_length=2)),
                ('TGRa', models.DateTimeField()),
                ('TGVao', models.DateTimeField(null=True)),
                ('DonVi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.donvimodel')),
            ],
        ),
        migrations.CreateModel(
            name='PCGacNgayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ngay', models.DateField()),
                ('CongGac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.conggacmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PCVeBinhModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.cagacvbmodel')),
                ('NgayCong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.pcgacngaymodel')),
            ],
        ),
        migrations.CreateModel(
            name='PCVeBinhChiTietModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChienSi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.chiensimodel')),
                ('PCVB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.pcvebinhmodel')),
            ],
        ),
        migrations.CreateModel(
            name='QNCNModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HoTen', models.CharField(max_length=50)),
                ('NgaySinh', models.DateField()),
                ('MaQuanNhan', models.CharField(max_length=20)),
                ('NgayNhapNgu', models.DateField()),
                ('SoCanCuoc', models.CharField(max_length=20)),
                ('QueQuan', models.CharField(max_length=60)),
                ('NoiO', models.CharField(max_length=60)),
                ('TrangThai', models.BooleanField(default=True)),
                ('CapBac', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.capbacmodel')),
                ('ChucVu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.cvqncnmodel')),
                ('DonVi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.donvimodel')),
                ('NhomQNCN', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.nhomqncnmodel')),
            ],
        ),
        migrations.CreateModel(
            name='QNCN_DVModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TuNgay', models.DateField()),
                ('DenNgay', models.DateField(null=True)),
                ('DV', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.donvimodel')),
                ('QNCN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.qncnmodel')),
            ],
        ),
        migrations.CreateModel(
            name='QNCN_CVModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TuNgay', models.DateField()),
                ('DenNgay', models.DateField(null=True)),
                ('CV', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.cvqncnmodel')),
                ('QNCN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.qncnmodel')),
            ],
        ),
        migrations.CreateModel(
            name='QuyenHVModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quyen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='model.quyenmodel')),
            ],
        ),
        migrations.CreateModel(
            name='QuyenNhomQNCNModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NhomQNCN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.nhomqncnmodel')),
                ('Quyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.quyenmodel')),
            ],
        ),
        migrations.CreateModel(
            name='QuyenNhomSQModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NhomSQ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.nhomsqmodel')),
                ('Quyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.quyenmodel')),
            ],
        ),
        migrations.CreateModel(
            name='QuyenNhomVCModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NhomVC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.nhomvcqpmodel')),
                ('Quyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.quyenmodel')),
            ],
        ),
        migrations.CreateModel(
            name='RNNgayHanhChinhModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LyDo', models.CharField(max_length=50)),
                ('DiaDiem', models.CharField(max_length=255)),
                ('TinhTrang', models.BooleanField(default=True)),
                ('HocVien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.hocvienmodel')),
            ],
        ),
        migrations.CreateModel(
            name='RNNHCThoiGianModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DKRa', models.DateTimeField()),
                ('DKVao', models.DateTimeField()),
                ('TGRa', models.DateTimeField(null=True)),
                ('TGVao', models.DateTimeField(null=True)),
                ('RNNgayHanhChinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.rnngayhanhchinhmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SiQuanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HoTen', models.CharField(max_length=50)),
                ('NgaySinh', models.DateField()),
                ('MaQuanNhan', models.CharField(max_length=20)),
                ('NgayNhapNgu', models.DateField()),
                ('SoCanCuoc', models.CharField(max_length=20)),
                ('QueQuan', models.CharField(max_length=60)),
                ('NoiO', models.CharField(max_length=60)),
                ('TrangThai', models.BooleanField(default=True)),
                ('CapBac', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.capbacmodel')),
                ('ChucVu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.cvsiquanmodel')),
                ('DonVi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.donvimodel')),
                ('NhomSQ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.nhomsqmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PCTrucBanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ngay', models.DateField()),
                ('TBPho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pctrucban_tbt', to='model.siquanmodel')),
                ('TBTruong', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pctrucban_tbp', to='model.siquanmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SQ_CVModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TuNgay', models.DateField()),
                ('DenNgay', models.DateField(null=True)),
                ('CV', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.cvsiquanmodel')),
                ('SQ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.siquanmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SQ_DVModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TuNgay', models.DateField()),
                ('DenNgay', models.DateField(null=True)),
                ('DV', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.donvimodel')),
                ('SQ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.siquanmodel')),
            ],
        ),
        migrations.CreateModel(
            name='KhachTDChiTietModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Khach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.khachmodel')),
                ('DoanKhach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.khachtheodoanmodel')),
                ('TheKhach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.thekhachmodel')),
            ],
        ),
        migrations.CreateModel(
            name='KhachSiQuanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThoiGianBatDau', models.DateTimeField()),
                ('ThoiGianKetThuc', models.DateTimeField(null=True)),
                ('GhiChu', models.CharField(max_length=255, null=True)),
                ('TraTheKhach', models.BooleanField(default=False)),
                ('Khach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.khachmodel')),
                ('SiQuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.siquanmodel')),
                ('TheKhach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.thekhachmodel')),
            ],
        ),
        migrations.CreateModel(
            name='KhachQNCNModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThoiGianBatDau', models.DateTimeField()),
                ('ThoiGianKetThuc', models.DateTimeField(null=True)),
                ('GhiChu', models.CharField(max_length=255, null=True)),
                ('TraTheKhach', models.BooleanField(default=False)),
                ('Khach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.khachmodel')),
                ('QNCN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.qncnmodel')),
                ('TheKhach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.thekhachmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TheQNCNModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoThe', models.CharField(max_length=5, unique=True)),
                ('TrangThai', models.BooleanField(default=True)),
                ('QNCN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.qncnmodel')),
            ],
        ),
        migrations.CreateModel(
            name='LSRaVaoQNCNModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThoiGian', models.DateTimeField()),
                ('TrangThai', models.BooleanField()),
                ('Cong', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.conggacmodel')),
                ('QNCN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.qncnmodel')),
                ('SoThe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.theqncnmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TheQNCNNamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nam', models.CharField(max_length=5)),
                ('The', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.theqncnmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TheSiQuanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoThe', models.CharField(max_length=5, unique=True)),
                ('TrangThai', models.BooleanField(default=True)),
                ('SiQuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.siquanmodel')),
            ],
        ),
        migrations.CreateModel(
            name='LSRaVaoSQModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThoiGian', models.DateTimeField()),
                ('TrangThai', models.BooleanField()),
                ('Cong', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.conggacmodel')),
                ('SiQuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.siquanmodel')),
                ('SoThe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.thesiquanmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TheSiQuanNamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nam', models.CharField(max_length=5)),
                ('The', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.thesiquanmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TheVienChucNamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nam', models.CharField(max_length=5)),
                ('The', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.thevienchucmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ThoiGianKhachTDModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DKVao', models.DateTimeField()),
                ('DKRa', models.DateTimeField()),
                ('TGVao', models.DateTimeField(null=True)),
                ('TGRa', models.DateTimeField(null=True)),
                ('DoanKhach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.khachtheodoanmodel')),
                ('SQDon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='model.siquanmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ThoiGianQuyenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Thu', models.IntegerField(choices=[(0, 'Thứ 2'), (1, 'Thứ 3'), (2, 'Thứ 4'), (3, 'Thứ 5'), (4, 'Thứ 6'), (5, 'Thứ 7'), (6, 'Chủ nhật')])),
                ('TGRa', models.TimeField()),
                ('TGVao', models.TimeField()),
                ('Quyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.quyenmodel')),
            ],
        ),
        migrations.CreateModel(
            name='VienChucQPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HoTen', models.CharField(max_length=50)),
                ('NgaySinh', models.DateField()),
                ('NgayBDLamViec', models.DateField()),
                ('SoCanCuoc', models.CharField(max_length=20)),
                ('QueQuan', models.CharField(max_length=60)),
                ('NoiO', models.CharField(max_length=60)),
                ('TrangThai', models.BooleanField(default=True)),
                ('DonVi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.donvimodel')),
                ('NhomVCQP', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.nhomvcqpmodel')),
            ],
        ),
        migrations.CreateModel(
            name='VC_DVModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TuNgay', models.DateField()),
                ('DenNgay', models.DateField(null=True)),
                ('DV', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.donvimodel')),
                ('VC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.vienchucqpmodel')),
            ],
        ),
        migrations.AddField(
            model_name='thevienchucmodel',
            name='VienChuc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.vienchucqpmodel'),
        ),
        migrations.CreateModel(
            name='LSRaVaoVCModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThoiGian', models.DateTimeField()),
                ('TrangThai', models.BooleanField()),
                ('Cong', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.conggacmodel')),
                ('SoThe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.thevienchucmodel')),
                ('VienChuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.vienchucqpmodel')),
            ],
        ),
        migrations.CreateModel(
            name='KhachVienChucModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThoiGianBatDau', models.DateTimeField()),
                ('ThoiGianKetThuc', models.DateTimeField(null=True)),
                ('GhiChu', models.CharField(max_length=255)),
                ('TraTheKhach', models.BooleanField(default=False)),
                ('Khach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.khachmodel')),
                ('TheKhach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.thekhachmodel')),
                ('VienChuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.vienchucqpmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ViPhamHVModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThoiGian', models.DateTimeField()),
                ('GhiChu', models.CharField(max_length=255)),
                ('Cong', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.conggacmodel')),
                ('HocVien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.hocvienmodel')),
                ('LoiViPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.loiviphammodel')),
            ],
        ),
        migrations.CreateModel(
            name='ViPhamQNCNModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThoiGian', models.DateTimeField()),
                ('GhiChu', models.CharField(max_length=255)),
                ('Cong', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.conggacmodel')),
                ('LoiViPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.loiviphammodel')),
                ('QNCN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.qncnmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ViPhamSQModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThoiGian', models.DateTimeField()),
                ('GhiChu', models.CharField(max_length=255)),
                ('Cong', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.conggacmodel')),
                ('LoiViPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.loiviphammodel')),
                ('SiQuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.siquanmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ViPhamVCModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThoiGian', models.DateTimeField()),
                ('GhiChu', models.CharField(max_length=255)),
                ('Cong', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.conggacmodel')),
                ('LoiViPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.loiviphammodel')),
                ('VienChuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.vienchucqpmodel')),
            ],
        ),
    ]
