# Generated by Django 5.1 on 2024-10-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donvimodel',
            name='tinhtrang',
            field=models.BooleanField(default=True),
        ),
    ]
