# Generated by Django 5.1 on 2024-08-27 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CongGacModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenCong', models.CharField(max_length=20)),
                ('ViTri', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LoaiKhachModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenLoaiKhach', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='khachmodel',
            old_name='SoCCCD',
            new_name='SoDinhDanh',
        ),
        migrations.RemoveField(
            model_name='pcvebinhmodel',
            name='Cong',
        ),
        migrations.AddField(
            model_name='theqncnmodel',
            name='TrangThai',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='thesiquanmodel',
            name='TrangThai',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='thevienchucmodel',
            name='TrangThai',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='capnhomdonvimodel',
            name='Cap',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='lsravaoqncnmodel',
            name='Cong',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='model.conggacmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lsravaosqmodel',
            name='Cong',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='model.conggacmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lsravaovcmodel',
            name='Cong',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='model.conggacmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pcvebinhmodel',
            name='CongGac',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='model.conggacmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='khachmodel',
            name='Loai',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='model.loaikhachmodel'),
            preserve_default=False,
        ),
    ]
