# Generated by Django 5.1 on 2024-08-27 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_conggacmodel_loaikhachmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SQ_CVModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TuNgay', models.DateField(auto_now_add=True)),
                ('DenNgay', models.DateField(null=True)),
                ('CV', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.cvsiquanmodel')),
                ('SQ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.siquanmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SQ_DVModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TuNgay', models.DateField(auto_now_add=True)),
                ('DenNgay', models.DateField(null=True)),
                ('DV', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.donvimodel')),
                ('SQ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.siquanmodel')),
            ],
        ),
    ]
