# Generated by Django 5.1 on 2024-08-27 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_sq_cvmodel_sq_dvmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='viphamhvmodel',
            name='Cong',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='model.conggacmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viphamqncnmodel',
            name='Cong',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='model.conggacmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viphamsqmodel',
            name='Cong',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='model.conggacmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viphamvcmodel',
            name='Cong',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='model.conggacmodel'),
            preserve_default=False,
        ),
    ]
