# Generated by Django 5.1 on 2024-08-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_viphamhvmodel_cong_viphamqncnmodel_cong_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhomdonvimodel',
            name='GhiChu',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
