# Generated by Django 5.1 on 2024-08-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_alter_nhomdonvimodel_ghichu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capnhomdonvimodel',
            name='Cap',
        ),
        migrations.AddField(
            model_name='capnhomdonvimodel',
            name='Ten',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
