# Generated by Django 5.1 on 2024-08-27 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_capnhomdonvimodel_cap_alter_capnhomdonvimodel_ten'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capnhomdonvimodel',
            name='Cap',
        ),
        migrations.AddField(
            model_name='capnhomdonvimodel',
            name='CapTren',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CapNhomTren', to='model.capnhomdonvimodel'),
        ),
    ]
