# Generated by Django 5.1 on 2024-08-27 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_remove_capnhomdonvimodel_cap_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvqncnmodel',
            name='id_NhomQNCN',
        ),
        migrations.RemoveField(
            model_name='cvsiquanmodel',
            name='id_NhomSQ',
        ),
    ]
