# Generated by Django 5.1 on 2024-08-27 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0009_remove_cvqncnmodel_id_nhomqncn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nhomqncnmodel',
            name='GhiChu',
        ),
        migrations.RemoveField(
            model_name='nhomsqmodel',
            name='GhiChu',
        ),
        migrations.RemoveField(
            model_name='nhomvcqpmodel',
            name='GhiChu',
        ),
    ]
