# Generated by Django 5.1 on 2024-08-28 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0010_remove_nhomqncnmodel_ghichu_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CBHaSiQuancModel',
            new_name='CBHaSiQuanModel',
        ),
        migrations.RemoveField(
            model_name='khachqncnmodel',
            name='CCKhach',
        ),
        migrations.RemoveField(
            model_name='khachqncnmodel',
            name='HoTenKhach',
        ),
        migrations.AddField(
            model_name='khachqncnmodel',
            name='GhiChu',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='khachqncnmodel',
            name='Khach',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='model.khachmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='khachqncnmodel',
            name='TheKhach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.thekhachmodel'),
        ),
        migrations.AlterField(
            model_name='khachsiquanmodel',
            name='GhiChu',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='KhachHocVienModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThoiGianBatDau', models.DateTimeField()),
                ('ThoiGianKetThuc', models.DateTimeField(null=True)),
                ('GhiChu', models.CharField(max_length=255, null=True)),
                ('HV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.hocvienmodel')),
                ('Khach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.khachmodel')),
            ],
        ),
    ]
