# Generated by Django 5.1 on 2024-08-29 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0011_rename_cbhasiquancmodel_cbhasiquanmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sq_cvmodel',
            name='SQ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.siquanmodel'),
        ),
        migrations.AlterField(
            model_name='sq_dvmodel',
            name='SQ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.siquanmodel'),
        ),
    ]
