# Generated by Django 5.1 on 2024-08-29 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0012_alter_sq_cvmodel_sq_alter_sq_dvmodel_sq'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheVienChucNamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nam', models.PositiveIntegerField()),
                ('The', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.thevienchucmodel')),
            ],
        ),
    ]
