# Generated by Django 5.1 on 2024-08-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0013_thevienchucnammodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quyenmodel',
            name='GiaiThich',
        ),
        migrations.AlterField(
            model_name='quyenmodel',
            name='TenQuyen',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
