# Generated by Django 5.1 on 2024-08-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0014_remove_quyenmodel_giaithich_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quyenmodel',
            name='GiaiThich',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quyenmodel',
            name='TenQuyen',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
