# Generated by Django 5.1 on 2024-08-29 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0015_quyenmodel_giaithich_alter_quyenmodel_tenquyen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thoigianquyenmodel',
            old_name='TGVap',
            new_name='TGVao',
        ),
    ]
