# Generated by Django 5.1 on 2024-08-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0016_rename_tgvap_thoigianquyenmodel_tgvao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thoigianquyenmodel',
            name='Thu',
            field=models.IntegerField(choices=[(0, 'Thứ Hai'), (1, 'Thứ Ba'), (2, 'Thứ Tư'), (3, 'Thứ Năm'), (4, 'Thứ Sáu'), (5, 'Thứ Bảy'), (6, 'Chủ Nhật')]),
        ),
    ]
