# Generated by Django 5.1 on 2024-08-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0017_alter_thoigianquyenmodel_thu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thekhachmodel',
            name='TrangThai',
            field=models.BooleanField(default=True),
        ),
    ]
