# Generated by Django 5.1 on 2024-08-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0018_alter_thekhachmodel_trangthai'),
    ]

    operations = [
        migrations.AddField(
            model_name='thekhachmodel',
            name='DangSuDung',
            field=models.BooleanField(default=False),
        ),
    ]
