# Generated by Django 5.1 on 2024-08-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0019_thekhachmodel_dangsudung'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaikhachmodel',
            name='TrangThai',
            field=models.BooleanField(default=True),
        ),
    ]
