# Generated by Django 5.1 on 2024-09-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0020_loaikhachmodel_trangthai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quyenmodel',
            name='TenQuyen',
            field=models.CharField(max_length=50),
        ),
    ]
