# Generated by Django 5.1 on 2024-09-02 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0021_alter_quyenmodel_tenquyen'),
    ]

    operations = [
        migrations.AddField(
            model_name='conggacmodel',
            name='TrangThai',
            field=models.BooleanField(default=True),
        ),
    ]
