# Generated by Django 5.1 on 2024-09-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0022_conggacmodel_trangthai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabacvcmodel',
            name='Ca',
            field=models.CharField(max_length=20),
        ),
    ]
