# Generated by Django 5.1 on 2024-09-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0023_alter_cabacvcmodel_ca'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabacvcmodel',
            name='TrangThai',
            field=models.BooleanField(default=True),
        ),
    ]
