# Generated by Django 5.1 on 2024-09-02 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0024_cabacvcmodel_trangthai'),
    ]

    operations = [
        migrations.AddField(
            model_name='chiensimodel',
            name='Ma',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pcvebinhchitietmodel',
            name='PCVB',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.pcvebinhmodel'),
        ),
    ]
