# Generated by Django 5.1 on 2024-09-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0025_chiensimodel_ma_alter_pcvebinhchitietmodel_pcvb'),
    ]

    operations = [
        migrations.AddField(
            model_name='chiensimodel',
            name='TrangThai',
            field=models.BooleanField(default=True),
        ),
    ]
