# Generated by Django 5.1 on 2024-09-02 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0026_chiensimodel_trangthai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcvebinhchitietmodel',
            name='ChienSi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.chiensimodel'),
        ),
    ]
