# Generated by Django 5.1 on 2024-09-02 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0027_alter_pcvebinhchitietmodel_chiensi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CaBacVCModel',
            new_name='CaGacVBModel',
        ),
        migrations.RemoveField(
            model_name='chiensimodel',
            name='TrangThai',
        ),
    ]
