# Generated by Django 5.1 on 2024-09-03 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0028_rename_cabacvcmodel_cagacvbmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcvebinhmodel',
            name='CongGac',
        ),
        migrations.RemoveField(
            model_name='pcvebinhmodel',
            name='Ngay',
        ),
        migrations.CreateModel(
            name='PCGacNgayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ngay', models.DateField()),
                ('CongGac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.conggacmodel')),
            ],
        ),
        migrations.AddField(
            model_name='pcvebinhmodel',
            name='NgayCong',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='model.pcgacngaymodel'),
            preserve_default=False,
        ),
    ]
