# Generated by Django 5.1 on 2024-09-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0029_remove_pcvebinhmodel_conggac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siquanmodel',
            name='TrangThai',
            field=models.BooleanField(default=True),
        ),
    ]
