# Generated by Django 5.1 on 2024-09-10 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0030_siquanmodel_trangthai'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CapNhomDonViModel',
            new_name='CapDonViModel',
        ),
    ]
