# Generated by Django 5.1 on 2024-09-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0031_rename_capnhomdonvimodel_capdonvimodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donvimodel',
            old_name='CapNhomDonVi',
            new_name='id_CapDonVi',
        ),
        migrations.AlterField(
            model_name='donvimodel',
            name='DiaDiem',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='donvimodel',
            name='MaDonVi',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
