# Generated by Django 5.1 on 2024-09-10 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0032_rename_capnhomdonvi_donvimodel_id_capdonvi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cvqncnmodel',
            old_name='id_CapNhomDonVi',
            new_name='id_CapDonVi',
        ),
        migrations.RenameField(
            model_name='cvsiquanmodel',
            old_name='id_CapNhomDonVi',
            new_name='id_CapDonVi',
        ),
    ]
