# Generated by Django 5.1 on 2024-09-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0033_rename_id_capnhomdonvi_cvqncnmodel_id_capdonvi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvqncnmodel',
            name='TinhTrang',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cvsiquanmodel',
            name='TinhTrang',
            field=models.BooleanField(default=True),
        ),
    ]
