# Generated by Django 5.1 on 2024-09-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0036_cbhasiquanmodel_tinhtrang'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhomsqmodel',
            name='TinhTrang',
            field=models.BooleanField(default=True),
        ),
    ]
