# Generated by Django 5.1 on 2024-09-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0037_nhomsqmodel_tinhtrang'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhomqncnmodel',
            name='TinhTrang',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nhomvcqpmodel',
            name='TinhTrang',
            field=models.BooleanField(default=True),
        ),
    ]
