# Generated by Django 5.1 on 2024-09-11 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0038_nhomqncnmodel_tinhtrang_nhomvcqpmodel_tinhtrang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sq_nhomsqmodel',
            name='NhomSiQuan',
        ),
        migrations.RemoveField(
            model_name='sq_nhomsqmodel',
            name='SiQuan',
        ),
        migrations.RemoveField(
            model_name='vc_nhomvcmodel',
            name='NhomVC',
        ),
        migrations.RemoveField(
            model_name='vc_nhomvcmodel',
            name='VienChuc',
        ),
        migrations.DeleteModel(
            name='QNCN_NhomQNCNModel',
        ),
        migrations.DeleteModel(
            name='SQ_NhomSQModel',
        ),
        migrations.DeleteModel(
            name='VC_NhomVCModel',
        ),
    ]
