# Generated by Django 5.1 on 2024-09-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0039_remove_sq_nhomsqmodel_nhomsiquan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theqncnnammodel',
            name='Nam',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='thesiquannammodel',
            name='Nam',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='thevienchucnammodel',
            name='Nam',
            field=models.CharField(max_length=5),
        ),
    ]
