# Generated by Django 5.1 on 2024-09-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0040_alter_theqncnnammodel_nam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loiviphammodel',
            name='TinhTrang',
            field=models.BooleanField(default=True),
        ),
    ]
