# Generated by Django 5.1 on 2024-09-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0041_loiviphammodel_tinhtrang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sq_cvmodel',
            name='TuNgay',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sq_dvmodel',
            name='TuNgay',
            field=models.DateField(),
        ),
    ]
