# Generated by Django 5.1 on 2024-09-11 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0042_alter_sq_cvmodel_tungay_alter_sq_dvmodel_tungay'),
    ]

    operations = [
        migrations.CreateModel(
            name='QNCN_CVModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TuNgay', models.DateField()),
                ('DenNgay', models.DateField(null=True)),
                ('CV', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.cvqncnmodel')),
                ('QNCN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.qncnmodel')),
            ],
        ),
        migrations.CreateModel(
            name='QNCN_DVModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TuNgay', models.DateField()),
                ('DenNgay', models.DateField(null=True)),
                ('DV', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.donvimodel')),
                ('QNCN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.qncnmodel')),
            ],
        ),
        migrations.CreateModel(
            name='VC_DVModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TuNgay', models.DateField()),
                ('DenNgay', models.DateField(null=True)),
                ('DV', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.donvimodel')),
                ('VC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.vienchucqpmodel')),
            ],
        ),
    ]
