# Generated by Django 5.1 on 2024-09-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0044_alter_thekhachmodel_sothe'),
    ]

    operations = [
        migrations.AddField(
            model_name='capdonvimodel',
            name='TinhTrang',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chiensimodel',
            name='TinhTrang',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hocvienmodel',
            name='TinhTrang',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='khachtheodoanmodel',
            name='TinhTrang',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='qncnmodel',
            name='TinhTrang',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quyenmodel',
            name='TinhTrang',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rnngayhanhchinhmodel',
            name='TinhTrang',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vienchucqpmodel',
            name='TrangThai',
            field=models.BooleanField(default=True),
        ),
    ]
