# Generated by Django 5.1 on 2024-09-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0045_capdonvimodel_tinhtrang_chiensimodel_tinhtrang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='khachqncnmodel',
            name='TraTheKhach',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='khachsiquanmodel',
            name='TraTheKhach',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='khachvienchucmodel',
            name='TraTheKhach',
            field=models.BooleanField(default=False),
        ),
    ]
